library(here)
library(sessioninfo)

outdir <- "spatialLIBD_files"
pkgname <- "spatialLIBD"

meta <- data.frame(
    Title = c(
        "habenula_atlas_HD_spe_cell",
        "habenula_atlas_HD_spe_cell_pseudobulk",
        "habenula_atlas_visium_spe",
        "habenula_atlas_visium_spe_pseudobulk",
        "habenula_atlas_snMultiome_seurat_cell",
        "habenula_atlas_snMultiome_seurat_metacell"
    ),
    Description = c(
        "SpatialExperiment object at the cell level for the habenula atlas human brain spatial transcriptomics data from the Visium HD platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "SpatialExperiment object pseudobulked by cell type for the habenula atlas human brain spatial transcriptomics data from the Visium HD platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "SpatialExperiment object at the spot level for the habenula atlas human brain spatial transcriptomics data from the Visium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "SpatialExperiment object pseudobulked at k = 9 for the habenula atlas human brain spatial transcriptomics data from the Visium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "Seurat object at the cell level for the habenula atlas human brain snMultiome (snATAC + snRNA-seq) data from the Chromium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "Seurat object at the metacell level for the habenula atlas human brain snMultiome (snATAC + snRNA-seq) data from the Chromium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package."
    ),
    BiocVersion = "3.23",
    Genome = "GRCh38",
    SourceType = "GTF",
    SourceUrl = "https://bioconductor.org/packages/spatialLIBD",
    SourceVersion = "Sep 25 2026",
    Species = "Homo sapiens",
    TaxonomyId = 9606,
    Coordinate_1_based = TRUE,
    DataProvider = "LIBD",
    Maintainer = "Leonardo Collado-Torres <lcolladotor@gmail.com>",
    RDataClass = c(
        "SpatialExperiment",
        "SpatialExperiment",
        "SpatialExperiment",
        "SpatialExperiment",
        "Seurat",
        "Seurat"
    ),
    DispatchClass = c("Rds", "Rds", "Rds", "Rds", "Rds", "Rds"),
    RDataPath = file.path(
        pkgname,
        outdir,
        c(
            "spe_cell_habenula_atlas.rds",
            "sce_pb_habenula_atlas.rds",
            "spe_visium_habenula_atlas.rds",
            "sce_pb_visium_habenula_atlas.rds",
            "seur_cell_snMultiome_habenula_atlas.rds",
            "seur_metacell_snMultiome_habenula_atlas.rds"
        )
    ),
    Tags = "habenulaAtlas_Visium_VisiumHD_snRNAseq_snATACseq_spatialLIBD",
    row.names = NULL,
    stringsAsFactors = FALSE
)

write.csv(
    meta, file = here("inst", "extdata", "metadata_habenula_atlas.csv"),
    row.names = FALSE
)

## Check
if (FALSE) {
    AnnotationHubData::makeAnnotationHubMetadata(
        here(), fileName = "metadata_habenula_atlas.csv"
    )
}

## Reproducibility information
print("Reproducibility information:")
Sys.time()
proc.time()
options(width = 120)
session_info()

# ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
#  setting  value
#  version  R version 4.6.1 Patched (2026-08-26 r90448)
#  os       Rocky Linux 9.4 (Blue Onyx)
#  system   x86_64, linux-gnu
#  ui       Positron
#  language (EN)
#  collate  en_US.UTF-8
#  ctype    en_US.UTF-8
#  tz       US/Eastern
#  date     2026-09-25
#  pandoc   3.10.2 @ /jhpce/shared/community/core/conda_R/4.6/bin/pandoc
#  quarto   NA

# ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
#  package              * version   date (UTC) lib source
#  abind                  1.4-8     2024-09-12 [2] CRAN (R 4.6.1)
#  AnnotationDbi          1.74.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  AnnotationForge        1.54.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  AnnotationHub          4.2.2     2026-07-02 [2] Bioconductor 3.23 (R 4.6.1)
#  AnnotationHubData      1.42.0    2026-04-28 [1] Bioconductor 3.23 (R 4.6.1)
#  Biobase                2.72.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  BiocBaseUtils          1.14.2    2026-05-28 [2] Bioconductor 3.23 (R 4.6.1)
#  BiocCheck              1.48.1    2026-07-02 [2] Bioconductor 3.23 (R 4.6.1)
#  BiocFileCache          3.2.0     2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  BiocGenerics           0.58.1    2026-05-14 [2] Bioconductor 3.23 (R 4.6.1)
#  BiocIO                 1.22.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  BiocManager            1.30.27   2025-11-14 [2] CRAN (R 4.6.1)
#  BiocParallel           1.46.0    2026-04-29 [2] Bioconductor 3.23 (R 4.6.1)
#  BiocVersion            3.23.1    2025-10-30 [2] Bioconductor 3.23 (R 4.6.1)
#  biocViews              1.80.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  Biostrings             2.80.1    2026-05-22 [2] Bioconductor 3.23 (R 4.6.1)
#  bit                    4.6.0     2025-03-06 [2] CRAN (R 4.6.1)
#  bit64                  4.8.4     2026-08-20 [2] CRAN (R 4.6.1)
#  bitops                 1.1-0     2026-07-30 [2] CRAN (R 4.6.1)
#  blob                   1.3.0     2026-01-14 [2] CRAN (R 4.6.1)
#  cachem                 1.1.0     2024-05-16 [2] CRAN (R 4.6.1)
#  callr                  3.8.0     2026-06-05 [2] CRAN (R 4.6.1)
#  cigarillo              1.2.1     2026-07-14 [2] Bioconductor 3.23 (R 4.6.1)
#  cli                    3.6.6     2026-04-09 [2] CRAN (R 4.6.1)
#  codetools              0.2-20    2024-03-31 [3] CRAN (R 4.6.1)
#  crayon                 1.5.3     2024-06-20 [2] CRAN (R 4.6.1)
#  curl                   8.0.0     2026-08-25 [2] CRAN (R 4.6.1)
#  DBI                    1.3.0     2026-02-25 [2] CRAN (R 4.6.1)
#  dbplyr                 2.6.0     2026-06-17 [2] CRAN (R 4.6.1)
#  DelayedArray           0.38.2    2026-05-26 [2] Bioconductor 3.23 (R 4.6.1)
#  dplyr                  1.2.1     2026-04-03 [2] CRAN (R 4.6.1)
#  evaluate               1.0.5     2025-08-27 [2] CRAN (R 4.6.1)
#  fastmap                1.2.0     2024-05-15 [2] CRAN (R 4.6.1)
#  filelock               1.0.3     2023-12-11 [2] CRAN (R 4.6.1)
#  formatR                1.14      2023-01-17 [2] CRAN (R 4.6.1)
#  futile.logger        * 1.4.9     2025-12-29 [2] CRAN (R 4.6.1)
#  futile.options         1.0.1     2018-04-20 [2] CRAN (R 4.6.1)
#  generics               0.1.4     2025-05-09 [2] CRAN (R 4.6.1)
#  GenomeInfoDb           1.48.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  GenomeInfoDbData       1.2.15    2026-09-25 [1] Bioconductor
#  GenomicAlignments      1.48.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  GenomicFeatures        1.64.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  GenomicRanges          1.64.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  glue                   1.8.1     2026-04-17 [2] CRAN (R 4.6.1)
#  graph                  1.90.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  here                 * 1.0.2     2025-09-15 [2] CRAN (R 4.6.1)
#  httr                   1.4.8     2026-02-13 [2] CRAN (R 4.6.1)
#  httr2                  1.3.0     2026-07-13 [2] CRAN (R 4.6.1)
#  IRanges                2.46.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  jsonlite               2.0.0     2025-03-27 [2] CRAN (R 4.6.1)
#  KEGGREST               1.52.2    2026-06-18 [2] Bioconductor 3.23 (R 4.6.1)
#  knitr                  1.51      2025-12-20 [2] CRAN (R 4.6.1)
#  lambda.r               1.2.4     2019-09-18 [2] CRAN (R 4.6.1)
#  lattice                0.23-1    2026-08-12 [3] CRAN (R 4.6.1)
#  lifecycle              1.0.5     2026-01-08 [2] CRAN (R 4.6.1)
#  magrittr               2.0.5     2026-04-04 [2] CRAN (R 4.6.1)
#  Matrix                 1.7-6     2026-07-25 [3] CRAN (R 4.6.1)
#  MatrixGenerics         1.24.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  matrixStats            1.5.0     2025-01-07 [2] CRAN (R 4.6.1)
#  memoise                2.0.1     2021-11-26 [2] CRAN (R 4.6.1)
#  OrganismDbi            1.54.0    2026-04-28 [1] Bioconductor 3.23 (R 4.6.1)
#  otel                   0.2.0     2025-08-29 [2] CRAN (R 4.6.1)
#  pak                    0.11.1    2026-07-22 [2] CRAN (R 4.6.1)
#  pillar                 1.11.1    2025-09-17 [2] CRAN (R 4.6.1)
#  pkgconfig              2.0.3     2019-09-22 [2] CRAN (R 4.6.1)
#  png                    0.1-9     2026-03-15 [2] CRAN (R 4.6.1)
#  processx               3.9.0     2026-04-22 [2] CRAN (R 4.6.1)
#  ps                     1.9.3     2026-04-20 [2] CRAN (R 4.6.1)
#  R6                     2.6.1     2025-02-15 [2] CRAN (R 4.6.1)
#  rappdirs               0.3.4     2026-01-17 [2] CRAN (R 4.6.1)
#  RBGL                   1.88.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  RCurl                  1.98-1.20 2026-08-21 [2] CRAN (R 4.6.1)
#  restfulr               0.0.17    2026-06-11 [2] CRAN (R 4.6.1)
#  rjson                  0.2.23    2024-09-16 [2] CRAN (R 4.6.1)
#  rlang                  1.3.0     2026-07-05 [2] CRAN (R 4.6.1)
#  rprojroot              2.1.1     2025-08-26 [2] CRAN (R 4.6.1)
#  Rsamtools              2.28.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  RSQLite                3.53.3    2026-06-30 [2] CRAN (R 4.6.1)
#  rtracklayer            1.72.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  RUnit                  0.4.33.1  2025-06-17 [2] CRAN (R 4.6.1)
#  S4Arrays               1.12.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  S4Vectors              0.50.2    2026-08-23 [2] Bioconductor 3.23 (R 4.6.1)
#  Seqinfo                1.2.0     2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  sessioninfo          * 1.2.4     2026-06-04 [2] CRAN (R 4.6.1)
#  SparseArray            1.12.2    2026-05-01 [2] Bioconductor 3.23 (R 4.6.1)
#  stringdist             0.9.17    2026-01-16 [2] CRAN (R 4.6.1)
#  SummarizedExperiment   1.42.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  tibble                 3.3.1     2026-01-11 [2] CRAN (R 4.6.1)
#  tidyselect             1.2.1     2024-03-11 [2] CRAN (R 4.6.1)
#  UCSC.utils             1.8.0     2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  vctrs                  0.7.3     2026-04-11 [2] CRAN (R 4.6.1)
#  xfun                   0.60      2026-07-09 [2] CRAN (R 4.6.1)
#  XML                    3.99-0.24 2026-08-21 [2] CRAN (R 4.6.1)
#  XVector                0.52.0    2026-04-28 [2] Bioconductor 3.23 (R 4.6.1)
#  yaml                   2.3.12    2025-12-10 [2] CRAN (R 4.6.1)

#  [1] /users/neagles/R/4.6
#  [2] /jhpce/shared/community/core/conda_R/4.6/R/lib64/R/site-library
#  [3] /jhpce/shared/community/core/conda_R/4.6/R/lib64/R/library
#  * ── Packages attached to the search path.

# ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
