library("here")
library("sessioninfo")


outdir <- "spatialLIBD_files"
pkgname <- "spatialLIBD"


meta <- data.frame(
    Title = c(
        "spatialDLPFC_Visium_spe",
        "spatialDLPFC_Visium_pseudobulk_spe",
        "spatialDLPFC_Visium_modeling_results",
        "spatialDLPFC_Visium_SPG",
        "spatialDLPFC_snRNAseq"
    ),
    Description = c(
        "SpatialExperiment object at the spot-level for the spatialDLPFC human brain (DLPFC) spatial transcriptomics data (n = 30) from the Visium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "Pseudo-bulked SingleCellExperiment object (SpatialExperiment object without spatial data) at the Sp09D spatial domain resolution for the spatialDLPFC human brain (DLPFC) spatial transcriptomics data (n = 30) from the Visium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "List of modeling results at the Sp09D spatial domain resolution for the spatialDLPFC human brain (DLPFC) spatial transcriptomics data (n = 30) from the Visium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "SpatialExperiment object at the spot-level for the spatialDLPFC human brain (DLPFC) spatial transcriptomics data (n = 4) from the Visium Spatial Proteogenomics (Visium-SPG) platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package.",
        "SingleCellExperiment object for the spatialDLPFC human brain (DLPFC) single nucleus transcriptomics data (snRNA-seq, n = 19) from the Chromium platform from 10x Genomics generated by the Lieber Institute for Brain Development (LIBD) and available through the spatialLIBD Bioconductor package."
    ),
    BiocVersion = "3.17",
    Genome = "GRCh38",
    SourceType = "GTF",
    SourceUrl = "https://bioconductor.org/packages/spatialLIBD",
    SourceVersion = "Feb 13 2022",
    Species = "Homo sapiens",
    TaxonomyId = 9606,
    Coordinate_1_based = TRUE,
    DataProvider = "LIBD",
    Maintainer = "Leonardo Collado-Torres <lcolladotor@gmail.com>",
    RDataClass = c(
        "SpatialExperiment",
        "SpatialExperiment",
        "list",
        "SpatialExperiment",
        "SingleCellExperiment"
    ),
    DispatchClass = c("Rds", "Rds", "Rda", "Rds", "FilePath"),
    RDataPath = file.path(
        pkgname,
        outdir,
        c(
            "spe_filtered_final_with_clusters_and_deconvolution_results.rds",
            "sce_pseudo_BayesSpace_k09.rds",
            "modeling_results_BayesSpace_k09.Rdata",
            "spe.rds",
            "sce_DLPFC_annotated.zip"
        )
    ),
    Tags = "spatialDLPFC_Visium_VisiumSPG_snRNAseq_spatialLIBD",
    row.names = NULL,
    stringsAsFactors = FALSE
)

write.csv(
    meta,
    file = here::here("inst", "extdata", "metadata_spatialDLPFC.csv"),
    row.names = FALSE
)

## Check
if (FALSE) {
    AnnotationHubData::makeAnnotationHubMetadata(here::here(), fileName = "metadata_spatialDLPFC.csv")
}

## Reproducibility information
print("Reproducibility information:")
Sys.time()
proc.time()
options(width = 120)
session_info()

