#' Convert a SCE object to a VE one
#'
#' This function converts a spot-level
#' [SingleCellExperiment-class][SingleCellExperiment::SingleCellExperiment-class]
#' (SCE) object as generated by `fetch_data()` to a
#'  [VisiumExperiment-class][SpatialExperiment::VisiumExperiment-class] (VE)
#'  object.
#'
#'  Note that the resulting object is a bit more complex than a regular VE
#'  because it contains the data for multiple images. Also, the VE validity
#'  code checks that the images files exist locally instead of being
#'  available remotely through a URL. Thus, we decided to download the images
#'  the moment the VE object is created. To deal with the fact that we have
#'  multiple images, we implemented the function `update_scaleFactors()` and
#'  `read_image()` which is used in the example of `geom_plot()`.
#'
#' @inheritParams run_app
#' @inheritParams fetch_data
#'
#' @return A a
#' [VisiumExperiment-class][SpatialExperiment::VisiumExperiment-class] object
#' with some customization for our data. See `update_scaleFactors()` for
#' more details.
#' @export
#' @family VisiumExperiment-related functions
#' @author
#' Brenda Pardo, Leonardo Collado-Torres
#'
#' @examples
#'
#' if (enough_ram()) {
#'     ## Download the sce data
#'     sce <- fetch_data("sce")
#'     ## Transform it to a VisiumExperiment object
#'     ve <- sce_to_ve(sce)
#' }
sce_to_ve <- function(sce = fetch_data("sce"), bfc = BiocFileCache::BiocFileCache()) {
    sce <- check_sce(sce)

    # Load assays
    assays_visium <- SummarizedExperiment::assays(sce)

    # Load rowData
    rowData_visium <- SummarizedExperiment::rowData(sce)

    # Load colData
    cols_to_drop <-
        c(
            "barcode",
            "sample_name",
            "tissue",
            "row",
            "col",
            "imagerow",
            "imagecol"
        )
    colData_visium <-
        SummarizedExperiment::colData(sce)[, !colnames(SummarizedExperiment::colData(sce)) %in% cols_to_drop, drop = FALSE]

    # Load spatialCoords
    spatialCoords_visium <-
        SummarizedExperiment::colData(sce)[, colnames(SummarizedExperiment::colData(sce)) %in% cols_to_drop, drop = FALSE]
    names(spatialCoords_visium) <-
        c(
            "Cell_ID",
            "sample_name",
            "in_tissue",
            "array_row",
            "array_col",
            "pxl_row_in_fullres",
            "pxl_col_in_fullres"
        )

    # Load reducedDim
    reducedDimNames_visium <-
        SingleCellExperiment::reducedDims(sce)

    # Load images
    sample_id <- unique(colData(sce)$sample_name)
    url_images <-
        paste0(
            "https://spatial-dlpfc.s3.us-east-2.amazonaws.com/images/",
            sample_id,
            "_tissue_lowres_image.png"
        )
    filepath_images <-
        BiocFileCache::bfcrpath(bfc, url_images, exact = TRUE)
    names(filepath_images) <- sample_id

    # Load scaleFactors
    url_scaleFactors <- paste0(
        "https://raw.githubusercontent.com/LieberInstitute/",
        "HumanPilot/master/10X/",
        sample_id,
        "/scalefactors_json.json"
    )
    names(url_scaleFactors) <- sample_id
    scaleFactors_visium <-
        lapply(url_scaleFactors, jsonlite::read_json)

    ## Create a list with the required 4 names by
    ## https://github.com/drighelli/SpatialExperiment/blob/master/R/Validity.R#L26-L28
    ## but also a 5th slot with the full list
    scaleFactors_visium_custom <- c(scaleFactors_visium[[1]],
        all_images = list(scaleFactors_visium)
    )

    ## Create object
    ve <- SpatialExperiment::VisiumExperiment(
        rowData = rowData_visium,
        colData = colData_visium,
        assays = assays_visium,
        spatialCoords = spatialCoords_visium,
        scaleFactors = scaleFactors_visium_custom,
        imagePaths = filepath_images,
        reducedDims = reducedDimNames_visium
    )
    return(ve)
}
